// libs/domain/src/ports/token-service.port.ts
// Outbound port that issues + verifies JWTs. Access tokens are short-lived (~15m) and
// carry the identity/role claims; refresh tokens are long-lived and carry a rotating
// (familyId, jti) pair that RefreshTokenStorePort uses for rotation + reuse detection.
// The domain never sees the signing algorithm or secrets — those live in the adapter.
import type { UserId, Locale, IsoDateTime } from './shared.dto';

/** Decoded claims of a valid ACCESS token. */
export interface AccessTokenClaims {
  readonly userId: UserId;
  readonly email: string;
  readonly role: string;
  readonly locale: Locale;
}

/** Decoded claims of a valid REFRESH token (rotation identity). */
export interface RefreshTokenClaims {
  readonly userId: UserId;
  readonly familyId: string;
  readonly jti: string;
}

export interface IssuedRefreshToken {
  readonly token: string;
  readonly jti: string;
  readonly familyId: string;
  readonly expiresAt: IsoDateTime;
}

export interface TokenServicePort {
  issueAccessToken(claims: AccessTokenClaims): Promise<string>;
  /** Mint a refresh token for a family + jti (both generated by the use case). */
  issueRefreshToken(params: {
    readonly userId: UserId;
    readonly familyId: string;
    readonly jti: string;
  }): Promise<IssuedRefreshToken>;
  /** Verify signature + expiry; returns claims, or `null` when invalid/expired. */
  verifyAccessToken(token: string): Promise<AccessTokenClaims | null>;
  verifyRefreshToken(token: string): Promise<RefreshTokenClaims | null>;
}
